spring.application.name=simplear

spring.r2dbc.url=r2dbc:mysql://localhost:3301/simplear
spring.r2dbc.username=app
spring.r2dbc.password=app

#Debugging
logging.level.org.springframework.r2dbc=DEBUG
logging.level.com.tweebs.simplear=DEBUG
logging.level.reactor.netty=WARN
logging.level.io.netty=WARN
