spring.application.name=simplear

spring.r2dbc.url=r2dbc:mysql://localhost:3301/simplear
spring.r2dbc.username=app
spring.r2dbc.password=app

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# HikariCP settings
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

#Debugging
logging.level.org.springframework.r2dbc=DEBUG
